


```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(gapminder)
library(car)
library(MASS)
library(caret)
library(psych)
# Read in Data
insurance <- read.csv("insurance.csv")
insurance_ori <-read.csv("insurance.csv")

##add new data point
new.data <- data.frame(22,"male", 17.32,0,"yes","southwest", 16003.29)
names(new.data) <- c("age", "sex", "bmi", "children","smoker","region","charges")
insurance <- rbind(insurance, new.data)

##change to factor
insurance$smoker=ifelse(insurance$smoker=="yes",1,0) # yes=1 no=0
insurance$sex <- as.numeric(factor(insurance$sex)) #female=1 male=2
insurance$region <- as.numeric(factor(insurance$region))#southwest=4,southeast=3,northwest=2,northeast=1;

```

```{r}
##hist
hist(insurance$age,xlab = "Age of Beneficiary",ylab = "Count",main = "Distribution of Age")
hist(insurance$children,xlab = "Number of Children",ylab = "Count",main = "Distribution of Number Of Children Covered By Medical Insurance")
hist(insurance$charges,xlab = "The cost of medical insurance",ylab = "count",main = "Distribution of insurance cost")
summary(insurance$charges)

hist(insurance$bmi,xlab = "BMI",ylab = "Count",main = "Distribution of BMI")
summary(insurance$bmi)
##bar chart
barchart(insurance_ori$smoker,col="black",xlab="Count",main="Bar chart of Smoker and Non-Smoker")
barchart(insurance_ori$region,col="black",xlab="Count",main="Bar chart of Region")
```
```{r}
#step1
#check missing value
mean(is.na(insurance))  # no missing value
```

```{r}
##indicator with age charges smoker
ggplot(insurance_ori,aes(x=age,y=charges,color=smoker)) +
  geom_point(aes(group=smoker))

mdl3=lm(charges~smoker,data=insurance)
mdl4=lm(charges~smoker+age+smoker*age,data=insurance)
print(anova(mdl3,mdl4))

```
```{r}
fit1 <- lm(charges ~ ., data=insurance) ##FUll model
fit2 <- lm(charges ~ 1, data=insurance) ##Base model

##backward
step(fit1,direction="backward") ##smoker age bmi children region

##both
step(fit2,direction="both",scope=list(upper=fit1,lower=fit2)) ##smoker age bmi children region
```
```{r}
#validation check   continue select predictor

#loop
##full model
set.seed(1411)

RMSPEfull<-NULL;
Rsqfull<-NULL;
MAPEfull<-NULL;

for(i in 1:10){
  
  n=nrow(insurance)
  nsamp=ceiling(0.7*n)
  training_samps=sample(c(1:n),nsamp)
  training_samps=sort(training_samps)
  train_data  <- insurance[training_samps, ]
  test_data <-   insurance[-training_samps, ]
  
  train.lm_full <- lm(charges ~ smoker+age+bmi+children+region, data = train_data) ##smoker age bmi children region
  
  preds <- predict(train.lm_full,test_data)
  
  
  Rsqfull[i] = R2(preds, test_data$charges)
  RMSPEfull[i] = RMSE(preds, test_data$charges)
  MAPEfull[i] = MAE(preds, test_data$charges)
}
mean(Rsqfull) 
mean(RMSPEfull)
mean(MAPEfull)
```
```{r}
##remove region
set.seed(12341)
RMSPE_sabc<-NULL;
Rsq_sabc<-NULL;
MAPE_sabc<-NULL;

for(i in 1:10){
  
  n=nrow(insurance)
  nsamp=ceiling(0.7*n)
  training_samps=sample(c(1:n),nsamp)
  training_samps=sort(training_samps)
  train_data  <- insurance[training_samps, ]
  test_data <-   insurance[-training_samps, ]
  
  train.lm_sabc <- lm(charges ~ smoker+age+bmi+children, data = train_data) ##smoker age bmi children
  
  preds1 <- predict(train.lm_sabc,test_data)
  
  
  Rsq_sabc[i] = R2(preds1, test_data$charges)
  RMSPE_sabc[i] = RMSE(preds1, test_data$charges)
  MAPE_sabc[i] = MAE(preds1, test_data$charges)
}
mean(Rsq_sabc)   
mean(RMSPE_sabc) 
mean(MAPE_sabc) 
```

```{r}
set.seed(987)
##remove children
RMSPE_sabr<-NULL;
Rsq_sabr<-NULL;
MAPE_sabr<-NULL;

for(i in 1:10){
  
  n=nrow(insurance)
  nsamp=ceiling(0.7*n)
  training_samps=sample(c(1:n),nsamp)
  training_samps=sort(training_samps)
  train_data  <- insurance[training_samps, ]
  test_data <-   insurance[-training_samps, ]
  
  train.lm_sabr <- lm(charges ~ smoker+age+bmi+region, data = train_data) ##smoker age bmi region
  
  preds2 <- predict(train.lm_sabr,test_data)
  
  
  Rsq_sabr[i] = R2(preds2, test_data$charges)
  RMSPE_sabr[i] = RMSE(preds2, test_data$charges)
  MAPE_sabr[i] = MAE(preds2, test_data$charges)
}
mean(Rsq_sabr)  
mean(RMSPE_sabr)
mean(MAPE_sabr)
```
```{r}
set.seed(5876)
##remove bmi
RMSPE_sacr<-NULL;
Rsq_sacr<-NULL;
MAPE_sacr<-NULL;

for(i in 1:10){
  
  n=nrow(insurance)
  nsamp=ceiling(0.7*n)
  training_samps=sample(c(1:n),nsamp)
  training_samps=sort(training_samps)
  train_data  <- insurance[training_samps, ]
  test_data <-   insurance[-training_samps, ]
  
  train.lm_sacr <- lm(charges ~ smoker+age+children+region, data = train_data) ##smoker age children region
  
  preds3 <- predict(train.lm_sacr,test_data)
  
  
  Rsq_sacr[i] = R2(preds3, test_data$charges)
  RMSPE_sacr[i] = RMSE(preds3, test_data$charges)
  MAPE_sacr[i] = MAE(preds3, test_data$charges)
}
mean(Rsq_sacr)  
mean(RMSPE_sacr) 
mean(MAPE_sacr)
```

```{r}
##remove age
set.seed(512876)
RMSPE_sbcr<-NULL;
Rsq_sbcr<-NULL;
MAPE_sbcr<-NULL;

for(i in 1:10){
  
  n=nrow(insurance)
  nsamp=ceiling(0.7*n)
  training_samps=sample(c(1:n),nsamp)
  training_samps=sort(training_samps)
  train_data  <- insurance[training_samps, ]
  test_data <-   insurance[-training_samps, ]
  
  train.lm_sbcr <- lm(charges ~ smoker+bmi+children+region, data = train_data) ##smoker bmi children region
  
  preds4 <- predict(train.lm_sbcr,test_data)
  
  
  Rsq_sbcr[i] = R2(preds4, test_data$charges)
  RMSPE_sbcr[i] = RMSE(preds4, test_data$charges)
  MAPE_sbcr[i] = MAE(preds4, test_data$charges)
}
mean(Rsq_sbcr)   
mean(RMSPE_sbcr) 
mean(MAPE_sbcr) 
```
```{r}
##remove smoker
set.seed(581476)
RMSPE_abcr<-NULL;
Rsq_abcr<-NULL;
MAPE_abcr<-NULL;

for(i in 1:10){
  
  n=nrow(insurance)
  nsamp=ceiling(0.7*n)
  training_samps=sample(c(1:n),nsamp)
  training_samps=sort(training_samps)
  train_data  <- insurance[training_samps, ]
  test_data <-   insurance[-training_samps, ]
  
  train.lm_abcr <- lm(charges ~ age+bmi+children+region, data = train_data) ##age bmi children region
  
  preds5 <- predict(train.lm_abcr,test_data)
  
  
  Rsq_abcr[i] = R2(preds5, test_data$charges)
  RMSPE_abcr[i] = RMSE(preds5, test_data$charges)
  MAPE_abcr[i] = MAE(preds5, test_data$charges)
}
mean(Rsq_abcr)   # 0.1213272
mean(RMSPE_abcr) # 11314.121
mean(MAPE_abcr) #  8980.853
```
```{r}
##final model: smoker age bmi children region
finalmdl<- lm(charges~smoker+age+bmi+children+region,data=insurance)
hist(resid(finalmdl),xlab = "Residuals",ylab="Count",main = "Distribution of Residuals") ##not normally distributed
plot(finalmdl,which=c(1,2,5)) ##not linear
```
```{r}

##Robust Regression
finalrrl= rlm(charges~smoker+age+bmi+children+region,data=insurance,psi=psi.huber)
hist(resid(finalrrl),xlab = "Residuals",ylab="Count",main = "Distribution of Residuals") ##not normally distributed
plot(finalrrl,which=c(1,2,5))

```
```{r}
##transformed

finalrrl_log=rlm(log(charges)~smoker+1/age+bmi+children+region,data=insurance,psi=psi.huber)

hist(resid(finalrrl_log),xlab = "Residuals",ylab="Count",main = "Distribution of Residuals") 

plot(finalrrl_log,which=c(1))
plot(finalrrl_log,which=c(2))
plot(finalrrl_log,which=c(5))

vif(finalrrl_log) ##check multicollinearity
```

```{r}

```

